// Generated by CoffeeScript 1.10.0
module.exports = function(obj) {
  return (function() {
    var __class, __prop;
    __class = (function() {
      var __args, ref;
      __args = Array.prototype.slice.call(arguments);
      if (this instanceof __class) {
        if (__class !== __class.prototype.constructor) {
          if ((ref = __class.prototype.constructor) != null) {
            ref.apply(this, __args);
          }
        }
        return this;
      } else {
        return new (Function.prototype.bind.apply(__class, [null].concat(__args)));
      }
    });
    __class.prototype = typeof this.prototype === 'function' ? Object.create(this.prototype.prototype) : this.prototype != null ? this.prototype : this;
    if (__class.prototype !== this) {
      for (__prop in this) {
        __class.prototype[__prop] = this[__prop];
      }
    }
    return __class;
  }).apply(obj);
};
